MegsoftEvaluation.Web/Controllers/BankAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MegsoftEvaluation.Web.Controllers
{
    [Authorize]
    public class BankAccountController : Controller
    {
        // GET: BankAccount
        public ActionResult Index()
        {
            return Dashboard();
        }

        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Manage()
        {
            return View();
        }

        public ActionResult Accounts()
        {
            return View();
        }

        public ActionResult Transactions()
        {
            return View();
        }

        public ActionResult Settings()
        {
            return View();
        }
    }
}

MegsoftEvaluation.Web/Views/Shared/_Empty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@ViewBag.Title</title>

    @Styles.Render("~/bundles/emptyCss")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="" />
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/icheck")
    @Scripts.Render("~/bundles/default")
    @RenderSection("scripts", required: false)
</body>
</html>

MegsoftEvaluation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@ViewBag.Title - Bank Monitor</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />

    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="skin-blue layout-boxed">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Home")" class="logo"><b>Bank</b>Monitor</a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Content/img/avatar5.png" class="user-image" alt="User Image" />
                                <span class="hidden-xs">@User.Identity.Name</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/Content/img/avatar5.png" class="img-circle" alt="User Image" />
                                    <p>
                                        @User.Identity.Name
                                        <small>Member since Mar. 2015</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="@Url.Action("Index","Manage")" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        @{ Html.RenderPartial("_LoginPartial"); }
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li>
                        <a href="@Url.Action("Dashboard", "BankAccount")">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-files-o"></i>
                            <span>Bank Accounts</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Accounts", "BankAccount")"><i class="fa fa-circle-o"></i> Accounts</a></li>
                            <li><a href="@Url.Action("Manage", "BankAccount")"><i class="fa fa-circle-o"></i> Manage</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Settings", "BankAccount")">
                            <i class="fa fa-th"></i> <span>Settings</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2009-@DateTime.Now.Year <a href="http://www.msp.do">Programador en .NET</a>.</strong>
        </footer>
    </div><!-- ./wrapper -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

    @Scripts.Render("~/bundles/app")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/default")
    @Scripts.Render("~/bundles/views")
    @RenderSection("scripts", required: false)
</body>
</html>